### PR TITLE
fix deprecation with catalina

### PR DESCRIPTION
**Pull request by tattali**

### CODE REVIEW

**Comment by tattali** [comment]
[QLMarkdown.qlgenerator.zip](https://github.com/toland/qlmarkdown/files/3752245/QLMarkdown.qlgenerator.zip)

**Comment by tattali** [comment]
#89

**Comment by tattali** [comment]
@toland @tarwich can you create a new release to update the homebrew cask version?
Thanks

**Comment by tarwich** [comment]
@tattali I would, but I don't have my Mac handy. Sorry about that. @toland ?

**Comment by tarwich** [comment]
Wait. Do we have to build it, or just create a release on GitHub to bump the version number?

**Comment by tattali** [comment]
Just a release with [this](https://github.com/toland/qlmarkdown/files/3752245/QLMarkdown.qlgenerator.zip) binary attached.
I can handle the update of the formula if you want

**Comment by tarwich** [comment]
Version [1.3.6](https://github.com/toland/qlmarkdown/releases/tag/v1.3.6) should be good to go, @tattali

**Comment by tattali** [comment]
Very nice! Thanks @tarwich !
I opened https://github.com/Homebrew/homebrew-cask/pull/71523 I think the bot will be merge it in few hours

**Comment by jspiro** [comment]
Screenshot 2019-10-28 at 10 21 35 PM

**Comment by tattali** [comment]
Try with #91 I don’t know why this binary doesn’t work

**Comment by bnussbau** [comment]
Also download with Safari browser. See https://github.com/toland/qlmarkdown/issues/89#issuecomment-547361530

**Pull request merged**
