### PR TITLE
Github markdown theme

### PR DESCRIPTION
**Pull request by tattali**
Use the actual github theme

### CODE REVIEW

**Comment by tarwich** [comment]
Should this be optional somehow, or should it be the way that qlmarkdown looks from now on?

**Comment by tattali** [comment]
Here, this is the way that qlmarkdown look, but make it an option can be very great.
Do you have an idea how to implement it?

**Comment by tattali** [comment]
maybe in command line that possible to choose the name of the resource file

**Comment by MaddTheSane** [comment]
Perhaps having the MarkDown page in an iframe?

Otherwise, I think you'd have to use `CFPreferences` if you wanted to use an application to set the default.

**Comment by tarwich** [comment]
Well I think it's fine, personally. The only reason I brought it up is because it's a big change to @toland 's product. If he's fine with it, we could merge, and just open an issue for the option to choose. Thoughts, @toland?

**Comment by toland** [comment]
> If he's fine with it, we could merge, and just open an issue for the option to choose.
I am fine. Let's do it.

:shipit:

**Pull request merged**
