### PR TITLE
#76 Allow theme switch

### PR DESCRIPTION
**Pull request by tattali**
like in #76 commit that allow theme switch
```sh
# NAME_OF_THEME = default|github
$ defaults write com.fiatdev.QLMarkdown theme NAME_OF_THEME
```

### CODE REVIEW

**Comment by toland** [comment]
LGTM. @tarwich any thoughts?

**Comment by tarwich** [comment]
LGTM. But I haven't tested it. Have you had a chance to do so, @toland ?

PS: I was shocked at how fast this change came through. It's exactly what we were talking about.

**Comment by toland** [comment]
> I haven't tested it. Have you had a chance to do so, @toland ?

Nope.

> I was shocked at how fast this change came through. It's exactly what we were talking about.

Indeed.

**Comment by tattali** [comment]
Hi,
I have not found any bugs but check it is more careful. [Help with defaults in osx](https://www.macissues.com/2014/03/25/how-to-properly-manipulate-defaults-in-os-x/)

Just be careful to clone : https://github.com/tattali/qlmarkdown.git
and not toland one (I did it once).

**Pull request closed without merging**
