### PR TITLE
add brew cask method

### PR DESCRIPTION
**Pull request by ctesniere**

### CODE REVIEW

**Comment by jpfairbanks** [comment]
I installed it by guessing that there was a cask for this.
The current text of the PR would install and then immediately uninstall.
If you say:

Another method, if you have `brew cask` :+1:
```bash
$ brew cask install qlmarkdown
```

To uninstall
```bash
$ brew cask uninstall qlmarkdown
```
Then a person just copying and pasting into the terminal won't mess it up.

**Comment by ctesniere** [comment]
Done

**Comment by jpfairbanks** [comment]
Thanks this should increase the visibility of this great plug in.

**Comment by tarwich** [comment]
If you get a chance, can you dump info into #52 please?

**Pull request merged**
